version: '3.9'

services:
  db:
    image: postgres:16.2
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books_db
    volumes:
      - ./.data/db:/var/lib/postgresql/data